server:
  port: 8080

spring:
  application:
    name: chat-service
  
  # 🛑 NAYA: localhost ki jagah 'postgres' likha hai
  datasource:
    url: jdbc:postgresql://postgres:5432/chatapp
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 🛑 NAYA: localhost ki jagah 'redis' likha hai
  data:
    redis:
      host: redis
      port: 6379

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

file:
  upload-dir: ./uploads/group-avatars

backend:
  base-url: http://localhost:8080

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG